export const consultations = [
  {
    id: 1,
    datetime: "2024-07-01T10:00:00Z",
    professional: "Dr. João Silva",
    professionalPicture: "https://randomuser.me/api/portraits/men/1.jpg",
    status: "Agendada",
  },
  {
    id: 2,
    datetime: "2024-07-02T14:30:00Z",
    professional: "Dra. Maria Souza",
    professionalPicture: "https://randomuser.me/api/portraits/women/2.jpg",
    status: "Confirmada",
  },
  {
    id: 3,
    datetime: "2024-07-03T09:00:00Z",
    professional: "Dr. Carlos Pereira",
    professionalPicture: "https://randomuser.me/api/portraits/men/3.jpg",
    status: "Cancelada",
  },
  {
    id: 4,
    datetime: "2024-07-04T16:15:00Z",
    professional: "Dra. Ana Lima",
    professionalPicture: "https://randomuser.me/api/portraits/women/4.jpg",
    status: "Realizada",
  },
  {
    id: 5,
    datetime: "2024-07-05T08:45:00Z",
    professional: "Dr. Pedro Alves",
    professionalPicture: "https://randomuser.me/api/portraits/men/5.jpg",
    status: "Agendada",
  },
  {
    id: 6,
    datetime: "2024-07-06T11:00:00Z",
    professional: "Dra. Beatriz Nunes",
    professionalPicture: "https://randomuser.me/api/portraits/women/6.jpg",
    status: "Confirmada",
  },
  {
    id: 7,
    datetime: "2024-07-07T15:30:00Z",
    professional: "Dr. Felipe Costa",
    professionalPicture: "https://randomuser.me/api/portraits/men/7.jpg",
    status: "Agendada",
  },
  {
    id: 8,
    datetime: "2024-07-08T13:15:00Z",
    professional: "Dra. Carla Mota",
    professionalPicture: "https://randomuser.me/api/portraits/women/8.jpg",
    status: "Realizada",
  },
  {
    id: 9,
    datetime: "2024-07-09T09:45:00Z",
    professional: "Dr. Lucas Ferreira",
    professionalPicture: "https://randomuser.me/api/portraits/men/9.jpg",
    status: "Cancelada",
  },
  {
    id: 10,
    datetime: "2024-07-10T17:00:00Z",
    professional: "Dra. Marina Rocha",
    professionalPicture: "https://randomuser.me/api/portraits/women/10.jpg",
    status: "Agendada",
  },
  {
    id: 11,
    datetime: "2024-07-11T10:30:00Z",
    professional: "Dr. Rafael Moreira",
    professionalPicture: "https://randomuser.me/api/portraits/men/11.jpg",
    status: "Confirmada",
  },
  {
    id: 12,
    datetime: "2024-07-12T12:00:00Z",
    professional: "Dra. Paula Fernandes",
    professionalPicture: "https://randomuser.me/api/portraits/women/12.jpg",
    status: "Agendada",
  },
  {
    id: 13,
    datetime: "2024-07-13T14:00:00Z",
    professional: "Dr. André Gomes",
    professionalPicture: "https://randomuser.me/api/portraits/men/13.jpg",
    status: "Realizada",
  },
  {
    id: 14,
    datetime: "2024-07-14T08:00:00Z",
    professional: "Dra. Juliana Alves",
    professionalPicture: "https://randomuser.me/api/portraits/women/14.jpg",
    status: "Cancelada",
  },
  {
    id: 15,
    datetime: "2024-07-15T16:45:00Z",
    professional: "Dr. Thiago Ramos",
    professionalPicture: "https://randomuser.me/api/portraits/men/15.jpg",
    status: "Agendada",
  },
];
